projects/mvcTemplate/Controllers/EventController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using mvc.Data;
using mvc.Models;

namespace mvc.Controllers
{

    public class EventController : Controller
    {
        private readonly ApplicationDbContext _context;

        // GET: EventController

        public EventController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index() // Affiche la vue Event
        {
            var Events = _context.Event.ToList();
            return View("~/Views/Event/Event.cshtml", Events);
        }

        [Authorize]
        public IActionResult Delete(string id) // supprime l'événement de la base de données
        {
            var eventItem = _context.Event.Find(int.Parse(id));
            if (eventItem != null)
            {
                _context.Event.Remove(eventItem);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult AddEvent() // Affiche la vue pour ajouter un événement
        {
            return View("~/Views/Event/AddEvent.cshtml");
        }

        [HttpPost]
        public IActionResult AddEvent(Event eventItem) // Ajoute un événement en base de données
        {
            if (eventItem == null)
            {
                return BadRequest("Event object is null.");
            }

            if (!ModelState.IsValid)
            {
                return View();
            }

            _context.Event.Add(eventItem);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

projects/mvcTemplate/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using mvc.Data;
using mvc.Models;

namespace mvc.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ApplicationDbContext _context;

        // GET: EventController

        public TeacherController(ApplicationDbContext context)
        {
            _context = context;
        }
        public ActionResult Index()
        {
            var Teachers = _context.Teacher.ToList();
            return View(Teachers);
        }

        public ActionResult Add()
        {
            return View("~/Views/Teacher/AddTeacher.cshtml");
        }

        [HttpPost]
        public IActionResult AddTeacher(Teacher teacher)
        {
            if (teacher == null)
            {
                return BadRequest("Teacher object is null.");
            }

            if (!ModelState.IsValid)
            {
                return View();
            }

            _context.Teacher.Add(teacher);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(string id) // supprime l'enseignant de la base de données
        {
            var teacher = _context.Teacher.Find(int.Parse(id));
            if (teacher != null)
            {
                _context.Teacher.Remove(teacher);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }


    }
}

projects/mvcTemplate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvc.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student"
                                asp-action="index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher"
                                asp-action="index">Teacher</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Event"
                                asp-action="index">Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                                asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                                asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                                asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>